version: '3.8'
services:
  prometheus:
    container_name: ${PROMETHEUS_CONTAINER}
    build: ./prometheus
    restart: always
    ports:
      - '${PROMETHEUS_PORT}:9090'
    expose:
      - '9090'
  grafana:
    container_name: ${GRAFANA_CONTAINER}
    build: ./grafana
    restart: always
    ports:
      - '${GRAFANA_PORT}:3000'
    expose:
      - '3000'
  sonarqube:
    container_name: ${SONARQUBE_CONTAINER}
    build: ./sonarqube
    restart: always
    ports:
      - '${SONARQUBE_PORT}:9000'
    expose:
      - '9000'
