version: '3.3'
services:
  mysql:
    env_file:
      - db.env
    container_name: ${MYSQL_CONTAINER}
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
  application:
    container_name: ${APPLICATION_CONTAINER}
    build: ../
    ports:
      - '8080:8080'
    expose:
      - '8080'
    profiles:
      - app
volumes:
  db:
