management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/client-api
    username: client-api
    password: client-api
    driver-class-name: com.mysql.cj.jdbc.Driver
